// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.8.2 DO NOT EDIT.
package api

// ApiResp defines model for ApiResp.
type ApiResp struct {
	Message string `json:"message"`
	Status  string `json:"status"`
}

// Bucket defines model for Bucket.
type Bucket struct {
	BucketName   string `json:"bucket_name"`
	CreationDate string `json:"creation_date"`
}

// Object defines model for Object.
type Object struct {
	ETag         *string `json:"e_tag,omitempty"`
	Key          *string `json:"key,omitempty"`
	LastModified *string `json:"last_modified,omitempty"`
	Size         *int    `json:"size,omitempty"`
}

